export default {
  // ─── Atoms ─────────────────────────────────────────────────────────────────
  '_atoms': { type: 'separator', title: 'Atoms' },
  'alert':             'Alert',
  'aspect-ratio':      'Aspect Ratio',
  'avatar':            'Avatar',
  'badge':             'Badge',
  'banking-window-dot': 'Banking Window Dot',
  'button':            'Button',
  'checkbox':          'Checkbox',
  'collapsible':       'Collapsible',
  'currency-badge':    'Currency Badge',
  'freshness-chip':    'Freshness Chip',
  'icon-button':       'Icon Button',
  'input':             'Input',
  'kbd':               'Kbd',
  'label':             'Label',
  'mono-amount':       'Mono Amount',
  'progress':          'Progress',
  'radio-group':       'Radio Group',
  'separator':         'Separator',
  'skeleton':          'Skeleton',
  'slider':            'Slider',
  'spinner':           'Spinner',
  'state-badge':       'State Badge',
  'status-pill':       'Status Pill',
  'status-ring':       'Status Ring',
  'switch':            'Switch',
  'tag':               'Tag',
  'textarea':          'Textarea',
  'toggle':            'Toggle',
  'typography':        'Typography',
  'urgency-badge':     'Urgency Badge',

  // ─── Molecules ─────────────────────────────────────────────────────────────
  '_molecules': { type: 'separator', title: 'Molecules' },
  'breadcrumb':    'Breadcrumb',
  'card':          'Card',
  'date-picker':   'Date Picker',
  'detail-card':   'Detail Card',
  'form':          'Form',
  'form-card':     'Form Card',
  'hover-card':    'Hover Card',
  'input-number':  'Input Number',
  'input-otp':     'Input OTP',
  'kpi-card':      'KPI Card',
  'pagination':    'Pagination',
  'popover':       'Popover',
  'resizable':     'Resizable',
  'scroll-area':   'Scroll Area',
  'segmented':     'Segmented',
  'select':        'Select',
  'stepper':       'Stepper',
  'tabs':          'Tabs',
  'toggle-group':  'Toggle Group',
  'tooltip':       'Tooltip',

  // ─── Organisms ─────────────────────────────────────────────────────────────
  '_organisms': { type: 'separator', title: 'Organisms' },
  'accordion':       'Accordion',
  'calendar':        'Calendar',
  'carousel':        'Carousel',
  'command':         'Command',
  'context-menu':    'Context Menu',
  'dialog':          'Dialog',
  'drawer':          'Drawer',
  'dropdown-menu':   'Dropdown Menu',
  'empty-state':     'Empty State',
  'navigation-menu': 'Navigation Menu',
  'sheet':           'Sheet',
  'sonner':          'Sonner',
  'table':           'Table',
  'timeline':        'Timeline',
};
